notOptimized:
	gcc -I/usr/local/include -L/usr/local/lib MultiplyMatrixMatrix.c -o MultiplyMatrixMatrix -lgsl -lgslcblas -lm

optimized:
	gcc -O2 -I/usr/local/include -L/usr/local/lib MultiplyMatrixMatrix.c -o MultiplyMatrixMatrix -lgsl -lgslcblas -lm
